name: TorchBench

# Add cronjob later
# Use workflow dispatch to manual trigger the job for now
on:
  workflow_dispatch:

jobs:
  TorchBenchCudaFull:
    uses: ./.github/workflows/reusable.yml
    with:
      name: torch-offcial-benchmark
      base_image: bladedisc/bladedisc:latest-runtime-torch1.12.0-cu113
      device: gpu-a10
      timeout_minutes: 4320 # 72h
      dockerfile: docker/cronjobs/Dockerfile.torch.bench
      extra_run_args: --cap-add=SYS_ADMIN --gpus all
      extra_envs: -e RELATED_DIFF_PERCENT=5
      exec_command: bash ./pytorch_blade/benchmark/TorchBench/test_torch_bench.sh cuda full
      push_command: ""
      remote_dev_docker: ""
    secrets: inherit
