name: TorchBench

# Add cronjob later
# Use workflow dispatch to manual trigger the job for now
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '30 15 * * *' # 11:30 pm UTC+8:00
    - cron: '30 15 * * 5' # 11:30 pm UTC+8:00 every Friday
  workflow_dispatch:
  push:

jobs:
  TorchBenchTiny:
    if: github.event.schedule != '30 15 * * 5' # daily or dispatch
    uses: ./.github/workflows/reusable.yml
    with:
      name: torch-offcial-benchmark
      base_image: bladedisc/bladedisc:latest-runtime-torch1.12.0-cu113
      device: gpu-a10
      dockerfile: docker/cronjobs/Dockerfile.torch.bench
      extra_run_args: --cap-add=SYS_ADMIN --gpus all
      extra_envs: -e OSS_ENDPOINT=${{ secrets.OSS_ENDPOINT }} -e OSS_AK=${{ secrets.OSS_AK }} -e OSS_SK=${{ secrets.OSS_SK }}
      exec_command: bash ./pytorch_blade/benchmark/TorchBench/test_torch_bench.sh tiny
      push_command: ""
      remote_dev_docker: ""
    secrets:
      ALIYUN_DOCKER_USERNAME: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
      ALIYUN_DOCKER_PASSWORD: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      OSS_ENDPOINT: ${{ secrets.OSS_ENDPOINT }}
      OSS_AK: ${{ secrets.OSS_AK }}
      OSS_SK: ${{ secrets.OSS_SK }}

  TorchBenchPartial:
    if: github.event.schedule == '30 15 * * *'
    uses: ./.github/workflows/reusable.yml
    with:
      name: torch-offcial-benchmark
      base_image: bladedisc/bladedisc:latest-runtime-torch1.12.0-cu113
      device: gpu-a10
      dockerfile: docker/cronjobs/Dockerfile.torch.bench
      extra_run_args: --cap-add=SYS_ADMIN --gpus all
      extra_envs: -e OSS_ENDPOINT=${{ secrets.OSS_ENDPOINT }} -e OSS_AK=${{ secrets.OSS_AK }} -e OSS_SK=${{ secrets.OSS_SK }}
      exec_command: bash ./pytorch_blade/benchmark/TorchBench/test_torch_bench.sh
      push_command: ""
      remote_dev_docker: ""
    secrets:
      ALIYUN_DOCKER_USERNAME: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
      ALIYUN_DOCKER_PASSWORD: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      OSS_ENDPOINT: ${{ secrets.OSS_ENDPOINT }}
      OSS_AK: ${{ secrets.OSS_AK }}
      OSS_SK: ${{ secrets.OSS_SK }}

  TorchBenchFull:
    if: github.event.schedule == '30 15 * * 5'
    uses: ./.github/workflows/reusable.yml
    with:
      name: torch-offcial-benchmark
      base_image: bladedisc/bladedisc:latest-runtime-torch1.12.0-cu113
      device: gpu-a10
      dockerfile: docker/cronjobs/Dockerfile.torch.bench
      extra_run_args: --cap-add=SYS_ADMIN --gpus all
      extra_envs: -e OSS_ENDPOINT=${{ secrets.OSS_ENDPOINT }} -e OSS_AK=${{ secrets.OSS_AK }} -e OSS_SK=${{ secrets.OSS_SK }}
      exec_command: bash ./pytorch_blade/benchmark/TorchBench/test_torch_bench.sh full
      push_command: ""
      remote_dev_docker: ""
    secrets:
      ALIYUN_DOCKER_USERNAME: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
      ALIYUN_DOCKER_PASSWORD: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      OSS_ENDPOINT: ${{ secrets.OSS_ENDPOINT }}
      OSS_AK: ${{ secrets.OSS_AK }}
      OSS_SK: ${{ secrets.OSS_SK }}

