name: TorchBench

# Add cronjob later
# Use workflow dispatch to manual trigger the job for now
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '30 15 * * *' # 11:30 pm UTC+8:00
    - cron: '30 15 * * 5' # 11:30 pm UTC+8:00 every Friday
  workflow_dispatch:

jobs:
  TorchBenchCudaFull:
    uses: ./.github/workflows/reusable.yml
    with:
      name: torch-offcial-benchmark
      base_image: bladedisc/bladedisc:latest-runtime-torch-pre-cu117
      device: gpu-bench
      timeout_minutes: 4320 # 72h
      dockerfile: docker/cronjobs/Dockerfile.torch.bench
      extra_run_args: --cap-add=SYS_ADMIN --gpus all
      extra_envs: -e RELATED_DIFF_PERCENT=5
      exec_command: bash ./pytorch_blade/benchmark/TorchBench/test_torch_bench.sh cuda full
      push_command: ""
      remote_dev_docker: ""
    secrets: inherit

  TorchBenchCpuFull:
    uses: ./.github/workflows/reusable.yml
    with:
      name: torch-offcial-benchmark
      base_image: bladedisc/bladedisc:latest-runtime-torch-pre-cpu
      device: bare_metal_x86
      timeout_minutes: 4320 # 72h
      dockerfile: docker/cronjobs/Dockerfile.torch.bench
      extra_envs: -e RELATED_DIFF_PERCENT=5
      exec_command: bash ./pytorch_blade/benchmark/TorchBench/test_torch_bench.sh cpu full
      push_command: ""
      remote_dev_docker: ""
    secrets: inherit

  TorchBenchAArch64Full:
    uses: ./.github/workflows/reusable.yml
    with:
      name: torch-offcial-benchmark
      base_image: bladedisc/bladedisc:latest-runtime-torch1.13.1-cpu-aarch64
      device: aarch64-bench
      timeout_minutes: 4320 # 72h
      dockerfile: docker/cronjobs/Dockerfile.torch.bench.aarch64
      extra_envs: -e RELATED_DIFF_PERCENT=5
      exec_command: bash ./pytorch_blade/benchmark/TorchBench/test_torch_bench.sh aarch64 full
      push_command: ""
      remote_dev_docker: ""
    secrets: inherit
